Format uk
OpenVoiceOS/ovos-lingua-franca pull request #50
Opened 2022-12-28 20:45 UTC by NeonMariia

2023-01-13 18:03 UTC, NeonDaniel commented
@NeonMariia I think these are the users you said could review this: @robinhad @VicGrygorchyk . I can't request reviews from non-maintainers, but anyone should be able to leave a review with comments.

If these changes look good to a native speaker, they are already passing unit tests so one of the maintainers here can merge it

2023-01-13 18:06 UTC, robinhad commented
Hi @NeonDaniel !
Thanks for adding me to this pull request. I have a dataset with cases for normalization, need some time to prepare it for evaluation and I'll get back to you.

2023-01-18 21:55 UTC, NeonDaniel commented
Associated PR for parsing: https://github.com/OpenVoiceOS/ovos-lingua-franca/pull/51

2023-01-26 18:38 UTC, JarbasAl commented
as mention in companion PR #51 

we just had a stable release and are back in alpha versions, I am ok with merging this as is and fix any issues in follow up PRs. This is great work and I'd like to get it in the wild!

Only see some debug prints to remove and maybe a rebase, there seems to be some duplicated code too between this and #51

2023-01-27 20:58 UTC, robinhad commented on lingua_franca/res/text/uk-uk/and.word
> +також
`та` could also be used as "and" word in Ukrainian
Ex: `Гензель та Гретель`

2023-01-27 21:01 UTC, robinhad commented on lingua_franca/res/text/uk-uk/normalize.json
> +    "нуль": "0",
should it have `"нуля": "0"` as in `5 градусів нижче нуля`?

2023-01-27 21:01 UTC, robinhad commented on lingua_franca/res/text/uk-uk/normalize.json
> +    "дві": "2",
and `двох` as well

2023-01-27 21:02 UTC, robinhad commented on lingua_franca/res/text/uk-uk/yesno.json
> +    "так",
should contain `та` - popular variant in western Ukraine

2023-01-27 21:03 UTC, robinhad commented on lingua_franca/res/text/uk-uk/yesno.json
> +    "не",
`нє` is a popular variant in western Ukraine

2023-01-27 21:03 UTC, robinhad commented on lingua_franca/res/text/uk-uk/yesno.json
> +    "задовільняє"
could be `можна` depending on context

2023-01-27 21:06 UTC, robinhad commented
Hi! Added a couple of comments with suggestion how to improve, overall looks great!

2023-04-06 15:19 UTC, robinhad approved these changes

2023-04-06 16:16 UTC, NeonDaniel commented
It looks like there are a few unaddressed comments, but n approving review from @robinhad. Should there be an issue to include those changes later, or are then intentionally not included?

I don't necessarily want to hold the PR for minor improvements but if they're valid, creating an issue will make sure we don't lose track of them.

2023-04-06 16:29 UTC, robinhad commented
Hi @NeonDaniel, they are valid, please include them in separate issue as improvements

2023-04-06 17:17 UTC, NeonDaniel commented
> Hi @NeonDaniel, they are valid, please include them in separate issue as improvements

Looks like another PR got most of them so I'll open an issue for the last couple before merging this one.

2023-04-06 17:58 UTC, emphasize commented on lingua_franca/lang/parse_common.py
> +    print(extract)
debug artifact

2023-04-06 18:33 UTC, emphasize commented on test/unittests/_trial_temp/_trial_marker
leftover file

2023-04-06 19:16 UTC, emphasize approved these changes

2023-04-06 20:14 UTC, ChanceNCounter commented on lingua_franca/res/text/uk-uk/and.word
> +також
This one appears to have been addressed

2023-04-06 20:26 UTC, ChanceNCounter commented on test/unittests/_trial_temp/_trial_marker
that whole directory, on review

2023-04-06 20:28 UTC, ChanceNCounter commented on lingua_franca/res/text/uk-uk/yesno.json
> +    "так",
added

2023-04-06 20:29 UTC, ChanceNCounter commented
On final review before merging, there only turned out to be one unresolved addition to the resource files, so I just threw that in. I also found one more stray tempfile directory, so I've removed that and re-requested @emphasize's review so as not to self-merge. Should be good to go.

2023-04-06 23:22 UTC, emphasize requested changes
All unittests are commented out, i don't think this is wanted

2023-04-06 23:37 UTC, emphasize approved these changes

2023-04-07 00:09 UTC, merged